config/routes.rb
Rails.application.routes.draw do
    resources :gossip
    resources :user
    resources :city
    resources :comment 
    resources :sessions, only: [:new, :create, :destroy]
    resources :like, only: [:show, :create, :destroy]
  

    # --- routes for about_us_controller ---
    get '/contact', to: 'about_us#contact'
    get '/team', to: 'about_us#team'    

    root 'gossip#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  
  has_many :users
  has_many :gossips, through: :users 

  validates :name, :zip_code, presence: true
  validates :zip_code,
  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :sub_comments

  validates :content, presence: true

end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments
  has_many :sub_comments, through: :comment
  has_many :likes

  validates :title, presence: true
  validates :content, presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

  validates :content, presence: true

end

app/models/sub_comment.rb
class SubComment < ApplicationRecord
  belongs_to :comment
  belongs_to :user

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links
end

app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  has_many :sub_comments
  has_many :likes

  has_secure_password

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  before_action :authenticate_user, only: [:create, :show, :new]
  before_action :authenticate_user_edit, only: [:edit, :update]


  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])

  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: current_user.id) 

    if @gossip.save 
      puts "Tu as réussi ! "
      redirect_to root_path
    else
      puts "Cela ne fontionne pas"
      render new_gossip_path
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_user = @gossip.user

    if @gossip.update(gossip_params)
      redirect_to root_path
    else
      render edit_gossip_path
    end
  end

  
  def destroy
    @gossip = Gossip.find(params[:id])
    gossip_user = @gossip.user

    if current_user == gossip_user
      @gossip.destroy
      redirect_to root_path
    else
      puts "Impossible"
    end
  end

end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
  
    # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
    elsif cookies[:user_id]
  
      # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
      user = User.find_by(id: cookies[:user_id])
  
      if user
  
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)
  
        if user_authenticated
          log_in user
          current_user = user
        end
  
      end
    end
  end
  
 
   def log_in(user)
    session[:user_id] = user.id
 end

  def remember(user)
    remember_token = SecureRandom.urlsafe_base64
  
     #j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end


  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
 end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/edit.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-white font-weight-bold">Modifier le potin <%= @user %>  !</h1>
    <p class="lead text-white font-weight-bold">Alors comme ça, on a changé d'avis ?</p>
</div>

</div>

<div class="row justify-content-center">
<div class="card create-potin" style="width: 40rem;">

<!-- REVOIR DESIGN FORMULAIRE-->

  <div class="card-body">
    <blockquote class="blockquote mb-1">
      <%= form_tag url_for(action: 'update'), method: "patch" do %>

      <div class="row justify-content-center">
        <%= label_tag 'Nouveau titre' %>
      </div>
        
        <div class="row justify-content-center">
         <%= text_field_tag 'title' %>
        </div>

        <br>

        <div class="row justify-content-center">
         <%= label_tag 'Nouveau contenu' %>
        </div>
        
        <div class="row justify-content-center">
         <%= text_area_tag 'content' %>
        </div>
        <br /> <br />

        <div class="row justify-content-center">
         <%= submit_tag "Envoyer" %>
        </div>

      <% end %>
    </blockquote>
  </div>
</div>
</div>

app/views/gossip/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <h1 class="display-4 text-white font-weight-bold">Bienvenue <%= @user %>  !</h1>
    <p class="lead text-white font-weight-bold">Retrouve tous nos potins en exclusivité et sois le premier au courant ! </p>
     <hr class="my-4">
     <p class="text-white">Tu veux faire un remake de Gossip Girl ? </p>
      <a class="btn btn-outline-light" href="<%=new_gossip_path %>" role="button">Clique ici</a>
</div>

<div class="row justify-content-center">
 <h4> Voici la liste des potins &#128133;</h4>
</div>

<div class="row">
  <% @gossips.each do |gossip| %>
    <div class="col-sm-3" style="padding: 20px">
      <div class="card">
        <div class="card-header">
          <h4><%= gossip.title %></h4>
        </div>
        <div class="card-body">
          <h5 class="card-title">Posté par  <%= gossip.user.first_name %></h5>
          <%= link_to "Voir le potin", gossip_path(gossip.id), class:"btn btn-outline-dark" %>
          
          <% if gossip.likes.where(user_id: current_user).count > 0 %>
            <%= link_to "Dislike", like_path(:id => gossip.likes.sample), method: :delete, class:"btn btn-secondary" %>
          <% else %>
            <%= link_to "Like", like_index_path(:id => gossip.id), method: :post, class:"btn btn-secondary" %>
          <% end %>
          <%= gossip.likes.count %>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/gossip/new.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-white font-weight-bold">Post un gossip <%= @user %>  !</h1>
    <p class="lead text-white font-weight-bold">On veut tout savoir ;)</p>
</div>


<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- REVOIR DESIGN FORMULAIRE-->

<div class="row justify-content-center">
<div class="card create-potin" style="width: 40rem;">


  <div class="card-body">
    <blockquote class="blockquote mb-1">
      <%= form_tag url_for(action: 'create'), method: "post" do %>

      <div class="row justify-content-center">
        <%= label_tag 'Titre de ton potin' %>
      </div>
        
        <div class="row justify-content-center">
         <%= text_field_tag 'title' %>
        </div>

        <br>

        <div class="row justify-content-center">
         <%= label_tag 'Contenu' %>
        </div>
        
        <div class="row justify-content-center">
         <%= text_area_tag 'content' %>
        </div>
        <br /> <br />

        <div class="row justify-content-center">
         <%= submit_tag "Envoyer" %>
        </div>

      <% end %>
    </blockquote>
  </div>
</div>
</div>

app/views/gossip/page.html.erb
<div class="card card-gossip">
  <div class="card-header">
    <H2><%= @gossip.title %></h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @gossip.content %></p>
      <footer class="blockquote-footer">Cet article a été écrit par "<%= @gossip.user.first_name %>" : <%= link_to "plus d'infos sur l'auteur", user_path(:user => @gossip.user.id) %></footer>
    </blockquote>
  </div>
</div>

app/views/gossip/show.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-white font-weight-bold">Potin complet</h1>
    <p class="lead text-white">Tous les détails. </p>
</div>




<div class="text-secondary row justify-content-center">
 <div class="card" style="width: 30rem;">
  <div class="card-header font-weight-bold text-center">
     <h3><%= @gossip.title %><h3>
  </div>
   <ul class="list-group list-group-flush">
    <li class="list-group-item text-center"><%= @gossip.content %>
    <li class="list-group-item text-center">Auteur : <%= link_to @gossip.user.first_name, user_path(@gossip.user.id) %>
    <li class="list-group-item text-center">Ville : <%= link_to @gossip.user.city.name, city_path(@gossip.user.city.id) %>
    </li>  
   </ul>
  </div>
</div>


   <br> 
    <p class="card-text text-center"><%= link_to "Modifier le potin", edit_gossip_path, class:"btn btn-outline-secondary" %> </p>
    <p class="card-text text-center"><%= link_to "Supprimer", gossip_path(@gossip.id), method: :delete, class:"btn btn-secondary"%></p>
  <br>
    <p class="card-text text-center"> <%= link_to "Revenir à la liste des potins", root_path %> </p>

<br>

<div class="row justify-content-center">
<div class="card create-potin" style="width: 58rem;">
  <div class="card-header">
    <h4>Laisser un commentaire</h4>
  </div>

  <br>

  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <%= form_tag url_for(controller: :comment, action: :create, id: @gossip.id), method: "post" do %>
        <%= label_tag '' %>
        <%= text_area_tag 'content' %>
        <br /> <br />
        <%= submit_tag "Ajouter un commentaire" %>
      <% end %>
    </blockquote>

    <br>

      <% @gossip.comments.each do |comment| %>
       <h5>Posté par <%= comment.user.first_name %> :</h5>
        <p><%= comment.content %>
        </p>
      <% end %>

  </div>
</div>
</div>


app/views/gossip/welcome.html.erb
<div class="container-fluid position-absolute mt-4 bg-light">
  <h2 class="text-center font-weight-bold">Welcome <%= @user %> !</h2>
  <p class="text-center">This is our gossip website. Here you can post, comment and show gossip.</p>
</div>